AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A basic Hello World API using SAM.

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello_world/app.lambda_handler # Points to your Python handler
      Runtime: python3.9
      CodeUri: ./hello_world/ # Directory containing your Lambda code
      MemorySize: 128
      Timeout: 3
      Events:
        HelloWorldApi:
          Type: Api # Defines an API Gateway trigger
          Properties:
            Path: /hello
            Method: get
Outputs: # Optional: to output the API endpoint URL after deployment
  HelloWorldApiUrl:
    Description: "API Gateway endpoint URL for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
